<a href="https://colab.research.google.com/github/djroyal-t/ml_nn_sandbox/blob/main/NNFS_Ch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install nnfs

In [11]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [12]:
nnfs.init()

In [14]:
# Dense layer
class Layer_Dense:

  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights, and biases
    self.output = np.dot(inputs, self.weights) + self.biases

In [16]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Perform a forward pass of our training data through this layer
dense1.forward(X)

# Let's see output of the first few samples:
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.3766826e-04 -1.1264831e-04 -8.7378961e-05]
 [ 2.2187467e-04 -6.7182438e-05 -8.6441352e-05]
 [ 4.0769580e-04 -3.1505432e-04 -2.4994812e-04]
 [ 5.4541085e-04 -4.2757124e-04 -3.3727608e-04]]
